NLP use-case template without Model Control Plan
zenml-io/template-nlp pull request #1
Opened 2023-10-28 15:38 UTC by safoinme

2023-10-28 16:45 UTC, htahir1 approved these changes
i would say we merge this and make a tag asap :-)

2023-10-28 16:46 UTC, htahir1 reviewed
The README could do with a bit of love to go into more detail

2023-11-01 09:44 UTC, strickvl requested changes
Looks really nice. I think once you take a look at these I'd want to test it out as well but basically looks good aside from these small nits.

2023-11-01 09:44 UTC, strickvl commented on template/pipelines/deploying.py
> +# Check if orchestrator flavor is either default or skypilot
this comment doesn't match what's below?

2023-11-01 09:44 UTC, strickvl commented on template/pipelines/training.py
> +    This is a pipeline that loads the datataset and tokenzier,
```suggestion
    This is a pipeline that loads the dataset and tokenizer,
```

2023-11-01 09:44 UTC, strickvl commented on template/requirements.txt
>  zenml[server]
do we need to pin a minimum zenml version for this template?

2023-11-01 09:44 UTC, strickvl commented on template/run.py
> +    "--depployment-app-title",
```suggestion
    "--deployment-app-title",
```

2023-11-01 09:44 UTC, strickvl commented on template/run.py
> +    "--depployment-app-title",
Also maybe change 'deployment' in all these flags to 'gradio'?

2023-11-01 09:44 UTC, strickvl commented on template/run.py
> +    "--depployment-app-example",
```suggestion
    "--deployment-app-description",
    default="Sentiment Analyzer",
    type=click.STRING,
    help="Description of the Gradio interface.",
)
@click.option(
    "--deployment-app-interpretation",
    default="default",
    type=click.STRING,
    help="Interpretation mode for the Gradio interface.",
)
@click.option(
    "--deployment-app-example",
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/dataset_loader/data_loader.py
> -    Args:
Needs `shuffle` arg that you added above?

2023-11-01 09:44 UTC, strickvl commented on template/steps/dataset_loader/data_loader.py
> +    {%- if dataset == 'imbd_reviews' %}
```suggestion
    {%- if dataset == 'imdb_reviews' %}
```

Not sure what this breaks, but I think it should be this way, no?

2023-11-01 09:44 UTC, strickvl commented on template/steps/deploying/save_model.py
> +    and tokenizer to the local filesystem, that will later then be used by the deployment
```suggestion
    and tokenizer to the local filesystem that will later then be used by the deployment
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/deploying/{% if deploy_locally %}local_deployment.py{% endif %}
> +    This step deploy the model locally by starting a Gradio app
```suggestion
    This step deploys the model locally by starting a Gradio app
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/deploying/{% if deploy_to_huggingface %}huggingface_deployment.py{% endif %}
> +    assert secret, "No secret found with name 'huggingface_creds'. Please create one with your `username` and `token`."
```suggestion
    assert secret, "No secret found with name 'huggingface_creds'. Please create one that includes your `username` and `token`."
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/deploying/{% if deploy_to_huggingface %}huggingface_deployment.py{% endif %}
> +    token = secret.secret_values["token"]
```suggestion
    huggingface_token = secret.secret_values["token"]
```

For consistency?

2023-11-01 09:44 UTC, strickvl commented on template/steps/deploying/{% if deploy_to_huggingface %}huggingface_deployment.py{% endif %}
> +    huggingface_username = secret.secret_values["username"]
We actually don't need this, right? It's not used anywhere below...

2023-11-01 09:44 UTC, strickvl commented on template/steps/deploying/{% if deploy_to_huggingface %}huggingface_deployment.py{% endif %}
> +            "You're running the `deploy_to_huggingface` step outside of a ZenML repo."
```suggestion
            "You're running the `deploy_to_huggingface` step outside of a ZenML repo. "
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/deploying/{% if deploy_locally %}local_deployment.py{% endif %}
> +            "You're running the `deploy_to_huggingface` step outside of a ZenML repo."
```suggestion
            "You're running the `deploy_to_huggingface` step outside of a ZenML repo. "
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/deploying/{% if deploy_to_skypilot %}skypilot_deployment.py{% endif %}
> +            "You're running the `deploy_to_huggingface` step outside of a ZenML repo."
```suggestion
            "You're running the `deploy_to_huggingface` step outside of a ZenML repo. "
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/deploying/{% if deploy_to_skypilot %}skypilot_deployment.py{% endif %}
> +            "this step will not work outside of a ZenML repo where the gradio folder is present."
```suggestion
            "this step will only work within a ZenML repo where the gradio folder is present."
```

Maybe clearer?

2023-11-01 09:44 UTC, strickvl commented on template/steps/promotion/{% if metric_compare_promotion %}promote_metric_compare_promoter.py{% endif %}
> +    metrics for 2 model version: latest and currently promoted to target environment
```suggestion
    metrics for two model versions, the latest and currently promoted to target environment
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/promotion/{% if metric_compare_promotion %}promote_metric_compare_promoter.py{% endif %}
> +    (Production, Staging, etc) and compare than in order to define
```suggestion
    (Production, Staging, etc) and compare them in order to check
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/promotion/{% if metric_compare_promotion %}promote_metric_compare_promoter.py{% endif %}
> +    version is better by metric - it will get relevant
```suggestion
    version is better as per the metric - it will get relevant
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/promotion/{% if metric_compare_promotion %}promote_metric_compare_promoter.py{% endif %}
> +    If the latest version is the only one - it will get promoted automatically.
```suggestion
    If the latest version is the only one, it will get promoted automatically.
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/promotion/{% if metric_compare_promotion %}promote_metric_compare_promoter.py{% endif %}
> +        current_version:Previously promoted model version.
```suggestion
        current_version: Previously promoted model version.
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/registrer/model_log_register.py
> +        "Your active stack needs to contain a MLFlow experiment tracker for "
```suggestion
        "Your active stack needs to contain an MLFlow experiment tracker for "
```

2023-11-01 09:44 UTC, strickvl commented on template/steps/registrer/model_log_register.py
> +        tokenizer: The tokenizer.
and the `mlflow_model_name` arg

2023-11-01 09:44 UTC, strickvl commented on template/utils/misc.py
> +def compute_metrics(eval_pred: tuple) -> dict[str, float]:
tuple of what?

2023-11-01 09:44 UTC, strickvl commented on template/utils/misc.py
> +    """Find the maximum length of the dataset.
Maybe this needs a bit more context in the docstring?

HF dataset? (since I guess it's unusual for datasets to be in a list of strings...)

2023-11-01 09:44 UTC, strickvl commented on README.md
> +| ZenML Server URL | Optional URL of a remote ZenML server for support scripts | - |
Do we use this anywhere?

2023-11-01 09:44 UTC, strickvl commented on README.md
> +zenml init --template nlp-template
```suggestion
zenml init --template template-nlp
```

I think?

2023-11-01 09:44 UTC, strickvl commented on README.md
> +zenml init --template nlp-template
Maybe I got that wrong, though...

2023-11-01 09:44 UTC, strickvl commented on README.md
> +The template includes a step for loading the dataset from the HuggingFace Datasets library. You can choose from three available datasets: financial_news, airline_reviews, and imbd_reviews.
```suggestion
The template includes a step for loading the dataset from the HuggingFace Datasets library. You can choose from three available datasets: financial_news, airline_reviews, and imdb_reviews.
```

See above. I think?

2023-11-01 09:44 UTC, strickvl commented on README.md
> +Once you have generated the project using this template, you can explore the generated code and customize it to fit your specific NLP use case. The README.md file in the generated project provides fu
Just realised that there's also this (`template/README.md`) that is already merged on the repo etc. I am not sure if it needs revising or not. Seems like maybe it does? In any case, probably needs attention.

2023-11-01 14:18 UTC, strickvl commented
Also since this is a template that'll be used in lots of different ways, might be worth making the extra effort to add docstrings etc in (+ maybe helped by darglint to make sure you've actually done it etc).

2023-11-03 09:54 UTC, merged